import React from "react";
import FilterAltIcon from "@mui/icons-material/FilterAlt";
import MoreHorizIcon from "@mui/icons-material/MoreHoriz";

export const exampleData = {
  dataLoad: {
    rows: [
      {
        id: 44,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000001",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:11.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Posted",
      },
      {
        id: 2,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:14.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Cancelled",
      },
      {
        id: 3,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T01:45:19.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 4,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 5,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000003",
        paytxn_no: "RV0000000003",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 6,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000004",
        paytxn_no: "RV0000000004",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 7,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000005",
        paytxn_no: "RV0000000005",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 8,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000006",
        paytxn_no: "RV0000000006",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 9,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000007",
        paytxn_no: "RV0000000007",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 10,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000008",
        paytxn_no: "RV0000000008",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
    ],
    rowsTotal: 1020,
    subtotal: 120000,
    grandTotal: 2000000,
    filterList: {
      "Customer ID-Name": [
        {
          customer_id: "ID01",
          customer_name: "John Wick",
        },
        {
          customer_id: "ID02",
          customer_name: "Sara Wick",
        },
        {
          customer_id: "ID03",
          customer_name: "Wick Wick",
        },
      ],
    },
  },
  dataIn: {
    values: {
      tab: "for-refunded",
    },
    loading: false,
    title: "Invoice",
    tabs: [
      {
        label: "Draft",
        value: "draft",
      },
      {
        label: "For Refunded",
        value: "for-refunded",
      },
    ],
    filterSection: {
      filterProps: {
        label: "Filter",
        icons: { startIcon: <FilterAltIcon /> },
        options: [
          {
            name: "Invoice Date",
            key: "invoice_date",
            type: "date",
          },
          {
            name: "Posting Date Range",
            key: "posting_date_range",
            type: "daterange",
          },
          {
            name: "Customer ID-Name",
            key: ["customer_id", "customer_name"],
            type: "select",
          },
        ],
      },
      searchProps: {},
      actionProps: {
        label: "More Action",
        icons: { startIcon: <MoreHorizIcon /> },
        options: [
          {
            name: "Export to PDF",
            action: () => console.log("Export PDF"),
          },
        ],
      },
      redirectionProps: {
        label: "Redirections",
        icons: { endIcon: <MoreHorizIcon /> },
        action: () => console.log("Redirect"),
      },
    },
    table: {
      overrideProps: { checkboxSelection: true },
      noTotal: false,
      selectionKey: "inv_no",
      columns: [
        {
          field: "payment_date",
          headerName: "Payment Date",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "paytxn_no",
          headerName: "Payment Transaction No.",
          minWidth: 220,
          flex: 1,
        },
        {
          field: "inv_no",
          headerName: "Invoice Number",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "customer_id",
          headerName: "Customer ID",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "fullname",
          headerName: "Customer Name",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_type",
          headerName: "Payment Type",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_method",
          headerName: "Payment Method",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "amount_paid",
          headerName: "Amount Paid",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "posted_date",
          headerName: "Posting Date",
          minWidth: 150,
          flex: 1,
        },
      ],
      actionBars: [
        {
          label: "Print Invoice",
          overrideProps: (i: any) => {
            return {
              disabled: false,
              onClick: () => console.log(i),
            };
          },
          action: (i: any) => console.log(i),
          disabled: false,
        },
        {
          label: "Send Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Publish Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Cancel Invoice",
          action: (i: any) => console.log(i),
        },
      ],
      rowActions: [
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: true,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
      ],
    },
  },
  dataOut: (val: any) => console.log(val),
};

export const exampleDataLSGH = {
  dataLoad: {
    rows: [
      {
        id: 44,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000001",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:11.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Posted",
      },
      {
        id: 2,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:14.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Cancelled",
      },
      {
        id: 3,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T01:45:19.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 4,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 5,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000003",
        paytxn_no: "RV0000000003",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 6,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000004",
        paytxn_no: "RV0000000004",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 7,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000005",
        paytxn_no: "RV0000000005",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 8,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000006",
        paytxn_no: "RV0000000006",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 9,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000007",
        paytxn_no: "RV0000000007",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 10,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000008",
        paytxn_no: "RV0000000008",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
    ],
    rowsTotal: 1020,
    subtotal: 120000,
    grandTotal: 2000000,
    filterList: {
      "Customer ID-Name": [
        {
          customer_id: "ID01",
          customer_name: "John Wick",
        },
        {
          customer_id: "ID02",
          customer_name: "Sara Wick",
        },
        {
          customer_id: "ID03",
          customer_name: "Wick Wick",
        },
      ],
    },
  },
  dataIn: {
    loading: false,
    title: "Invoice",
    tabs: [
      {
        label: "Draft",
        value: "draft",
      },
      {
        label: "For Refunded",
        value: "for-refunded",
      },
    ],
    filterSection: {
      filterProps: {
        options: [
          {
            name: "Invoice Date",
            key: "invoice_date",
            type: "date",
          },
          {
            name: "Posting Date Range",
            key: "posting_date_range",
            type: "daterange",
          },
          {
            name: "Customer ID-Name",
            key: ["customer_id", "customer_name"],
            type: "select",
          },
        ],
      },
      searchProps: {},
      actionProps: {
        options: [
          {
            name: "Export to PDF",
            action: () => console.log("Export PDF"),
          },
        ],
      },
      redirectionProps: {
        label: "+ Create Invoice",
        action: () => console.log("Redirect"),
      },
    },
    table: {
      overrideProps: { checkboxSelection: true },
      noTotal: false,
      selectionKey: "inv_no",
      columns: [
        {
          field: "payment_date",
          headerName: "Payment Date",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "paytxn_no",
          headerName: "Payment Transaction No.",
          minWidth: 220,
          flex: 1,
        },
        {
          field: "inv_no",
          headerName: "Invoice Number",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "customer_id",
          headerName: "Customer ID",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "fullname",
          headerName: "Customer Name",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_type",
          headerName: "Payment Type",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_method",
          headerName: "Payment Method",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "amount_paid",
          headerName: "Amount Paid",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "posted_date",
          headerName: "Posting Date",
          minWidth: 150,
          flex: 1,
        },
      ],
      actionBars: [
        {
          label: "Print Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Send Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Publish Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Cancel Invoice",
          action: (i: any) => console.log(i),
        },
      ],
      rowActions: [
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: true,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
        },
      ],
    },
    styles: {
      // Tabs Style
      tabs: {
        background: "unset",

        ".MuiOutlinedInput-root": {
          background: "#fff",
        },
        ".MuiDataGrid-columnHeaders": {
          background: "unset",
          textTransform: "uppercase",
        },
        ".MuiDataGrid-row": {
          background: "#fff",
          margin: "2px 0",
          "&:nth-of-type(even)": {
            background: "#fff",
            margin: "2px 0",
          },
        },
      },
      header: {
        ".Mui-selected": {
          color: "unset",
          fontWeight: 600,
        },
      },
      // Filter Style
      filtersection: {
        ".MuiGrid-item:nth-child(3) .dropdownbutton": {
          background: "#058CB1",
          color: "#fff",
          fontWeight: 600,
        },
      },
      dropdownbutton: {
        background: "#fff",
        color: "unset",
        borderRadius: "0px",
        border: "1px solid #D0D7E2",
      },
      searchfield: {
        background: "#fff",
        border: "1px solid #D0D7E2",
        padding: "6.5px 0px 6.5px 5px",
      },
    },
  },
  dataOut: (val: any) => console.log(val),
};

export const initialDataOut = {
  filters: { search: "" },
  pagination: { page: 1, limit: 10 },
  sorting: { sort: "id", order: "asc" },
  status: "draft",
};

export const exampleDataRNR = {
  dataLoad: {
    rows: [
      {
        id: 44,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000001",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:11.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Posted",
      },
      {
        id: 2,
        customer_id: "SMS0100000001",
        fullname: "Diane Sy",
        inv_no: "INV0000000010",
        paytxn_no: "RV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-28T07:59:14.000Z",
        payment_method: "Check",
        bank_code: "BDO",
        payment_type: "Regular Payment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Cancelled",
      },
      {
        id: 3,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T01:45:19.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 4,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000002",
        paytxn_no: "INV0000000002",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-04-01",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BPI",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: "Nothing special",
        api_response: null,
        status: "Posted",
      },
      {
        id: 5,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000003",
        paytxn_no: "RV0000000003",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 6,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000004",
        paytxn_no: "RV0000000004",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 7,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000005",
        paytxn_no: "RV0000000005",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 8,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000006",
        paytxn_no: "RV0000000006",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 9,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000007",
        paytxn_no: "RV0000000007",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
      {
        id: 10,
        customer_id: "SMS0100000002",
        fullname: "Diane Sy",
        inv_no: "INV0000000008",
        paytxn_no: "RV0000000008",
        payrcpt_no: null,
        payrefdoc_no: "PRD0000000002",
        posted_date: "2022-03-31",
        cancelled_date: null,
        refunded_date: null,
        payment_date: "2022-03-31T04:54:13.000Z",
        payment_method: "Bank Transfer",
        bank_code: "BDO",
        payment_type: "Overpayment",
        amount_paid: "3000.00",
        payment_received_by: null,
        notes: null,
        api_response: null,
        status: "Unposted",
      },
    ],
    rowsTotal: 1020,
    subtotal: 120000,
    grandTotal: 2000000,
    filterList: {
      "Customer ID-Name": [
        {
          customer_id: "ID01",
          customer_name: "John Wick",
        },
        {
          customer_id: "ID02",
          customer_name: "Sara Wick",
        },
        {
          customer_id: "ID03",
          customer_name: "Wick Wick",
        },
      ],
    },
  },
  dataIn: {
    loading: false,
    title: "Invoice",
    tabs: [
      {
        label: "Draft",
        value: "draft",
      },
      {
        label: "For Refunded",
        value: "for-refunded",
      },
    ],
    filterSection: {
      filterProps: {
        options: [
          {
            name: "Invoice Date",
            key: "invoice_date",
            type: "date",
          },
          {
            name: "Posting Date Range",
            key: "posting_date_range",
            type: "daterange",
          },
          {
            name: "Customer ID-Name",
            key: ["customer_id", "customer_name"],
            type: "select",
          },
        ],
      },
      searchProps: {
        string: 1,
      },
      actionProps: {
        options: [
          {
            name: "Export to PDF",
            action: () => console.log("Export PDF"),
          },
        ],
        autoClose: true,
      },
      redirectionProps: {
        label: "+ Create Invoice",
        action: () => console.log("Redirect"),
      },
    },
    table: {
      overrideProps: { checkboxSelection: true },
      noTotal: false,
      selectionKey: "inv_no",
      columns: [
        {
          field: "payment_date",
          headerName: "Payment Date",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "paytxn_no",
          headerName: "Payment Transaction No.",
          minWidth: 220,
          flex: 1,
        },
        {
          field: "inv_no",
          headerName: "Invoice Number",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "customer_id",
          headerName: "Customer ID",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "fullname",
          headerName: "Customer Name",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_type",
          headerName: "Payment Type",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "payment_method",
          headerName: "Payment Method",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "amount_paid",
          headerName: "Amount Paid",
          minWidth: 150,
          flex: 1,
        },
        {
          field: "posted_date",
          headerName: "Posting Date",
          minWidth: 150,
          flex: 1,
        },
      ],
      actionBars: [
        {
          label: "Print Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Send Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Publish Invoice",
          action: (i: any) => console.log(i),
        },
        {
          label: "Cancel Invoice",
          action: (i: any) => console.log(i),
        },
      ],
      rowActions: [
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
          autoClose: true,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
          autoClose: true,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: true,
          autoClose: true,
        },
        {
          label: "Print",
          action: (i: any) => console.log(i),
          divider: false,
          autoClose: true,
        },
      ],
    },
    styles: {
      // Tabs Style
      tabs: {
        background: "unset",

        ".MuiOutlinedInput-root": {
          background: "#fff",
        },
        ".MuiDataGrid-columnHeaders": {
          background: "unset",
          textTransform: "uppercase",
        },
        ".MuiDataGrid-row": {
          background: "#fff",
          margin: "2px 0",
          "&:nth-of-type(even)": {
            background: "#fff",
            margin: "2px 0",
          },
        },
      },
      header: {
        ".Mui-selected": {
          color: "unset",
          fontWeight: 600,
        },
      },
      // Filter Style
      filtersection: {
        ".MuiGrid-item:nth-child(3) .dropdownbutton": {
          background: "#058CB1",
          color: "#fff",
          fontWeight: 600,
        },
      },
      dropdownbutton: {
        background: "#fff",
        color: "unset",
        borderRadius: "0px",
        border: "1px solid #D0D7E2",
      },
      searchfield: {
        background: "#fff",
        border: "1px solid #D0D7E2",
        padding: "6.5px 0px 6.5px 5px",
      },
    },
  },
  dataOut: (val: any) => console.log(val),
};
