export const SET_TAB = "SET_TAB";

export const SET_FILTER = "SET_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

export const SET_DEFAUlT_CHECKBOX = "SET_DEFAUlT_CHECKBOX";
export const SET_FILTER_CHECKBOX = "SET_FILTER_CHECKBOX";
export const REMOVE_FILTER_CHECKBOX = "REMOVE_FILTER_CHECKBOX";

export const CHANGE_PAGINATION = "CHANGE_PAGINATION";

export const SORTING = "SORTING";

export const SET_CHECKBOX = "SET_CHECKBOX";
export const SET_SELECTION = "SET_SELECTION";
export const SET_SELECTION_DATA = "SET_SELECTION_DATA";
export const REMOVE_ALL_CHECKBOX = "REMOVE_ALL_CHECKBOX";

export const SET_VALUES = "SET_VALUES";
